package main

import (
	"log"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"github.com/vgaro/yotocli/cmd"
)

func main() {
	dir := "./docs/commands"
	if err := GenerateDocs(dir); err != nil {
		log.Fatal(err)
	}
	log.Printf("Documentation generated in %s\n", dir)
}

// GenerateDocs generates markdown documentation for all commands in the specified directory.
func GenerateDocs(dir string) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	root := cmd.RootCmd()
	// Disable timestamp generation to avoid git churn whenever docs are regenerated.
	disableAutoGenTag(root)

	return doc.GenMarkdownTree(root, dir)
}

// disableAutoGenTag suppresses the "Auto generated by spf13/cobra on <date>" footer
// across all commands to avoid unnecessary git churn from timestamp updates.
func disableAutoGenTag(c *cobra.Command) {
	c.DisableAutoGenTag = true
	for _, child := range c.Commands() {
		disableAutoGenTag(child)
	}
}

